--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cosmoverse/WorldBuilder
branches:
- master
projects:
  WorldBuilder:
    path: ""
    libs:
      - src: SOF3/await-generator/await-generator
        version: ^3.6.1
...
