# WorldBuilder v0.0.1 configuration

# The maximum number of blocks that can be iterated over a tick.
# Decreasing this will slow down world editor processes.
# Increasing this will speed up world editor processes but may decrease server TPS
max-ops-per-tick: 65536